version: '3.7'

services: 
    web:
        build: .
        command: python /app/contactmemng/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/app
        ports: 
            - 8000:8000
        depends_on: 
            - migration
    migration:
        build: .
        command: sh -c " python /app/contactmemng/manage.py migrate"
        volumes: 
            - .:/app