version: "3.7"

services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose:
            - "5432"
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        command: sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        depends_on:
            - db
volumes:
    pgdata:
