version: '3.7'

services: 
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose: 
            - "5432"
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        command: python /app/contactmemng/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/app
        ports: 
            - 8000:8000
        depends_on: 
            - migration
            - db
    migration:
        build: 
            context: .
            dockerfile: Dockerfile
            target: prod
        command: sh -c "python /app/contactmemng/manage.py makemigrations && python /app/contactmemng/manage.py migrate"
        volumes: 
            - .:/app
        depends_on: 
            - db
volumes: 
    pgdata: