version: "3.7"

services:
    db:
        image: postgres:12-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose:
            - "5432"
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        command: sh -c "python ./contactmemng/manage.py migrate --no-input && python ./contactmemng/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - 8000:8000
        depends_on:
            - db
            - webpack
    webpack:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        command: npm start
        volumes:
            - .:/app:rw
            - node_modules:/app/node_modules
        ports:
            - 8080:8080
        depends_on:
            - db
volumes:
    pgdata:
    node_modules:
